"""Create APILog table

Revision ID: 730d5d9c35f8
Revises: 
Create Date: 2024-06-18 16:47:25.927438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730d5d9c35f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('request_data', sa.Text(), nullable=False),
    sa.Column('response_data', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_log')
    # ### end Alembic commands ###
